# Generated by Django 5.2.14 on 2026-09-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_online_training", "0005_alter_traininguser_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="answer_key",
            field=models.JSONField(
                blank=True,
                help_text="<p>JSON mapping of inputs to correct answers. Leave blank to only require completion.</p><p>Entries starting with _ are ignored during grading. This can be used to pass an email address or list to send quiz results</p>",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="max_attempts",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Maximum allowed attempts. Set to 0 or leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="passing_score_percentage",
            field=models.IntegerField(
                blank=True, help_text="Required score to pass (e.g. 80). Leave blank if no quiz is required.", null=True
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="retry_cooldown_minutes",
            field=models.IntegerField(
                blank=True, default=0, help_text="Wait time in minutes between failed attempts.", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="cleared_for_retake",
            field=models.BooleanField(
                default=False, help_text="If True, the user is permitted to attempt this training again after failing."
            ),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="failed",
            field=models.BooleanField(
                default=False, help_text="Indicates if the user has exhausted all attempts and failed."
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="html_content",
            field=models.TextField(
                blank=True,
                help_text="<p>The HTML content of the training. The following context variables are available:</p><ul style='padding-left: 35px;'><li style='list-style: initial'><b>training_user</b>: the user who is completing the training</li><li style='list-style: initial'><b>training</b>: the training being completed</li><li style='list-style: initial'><b>record</b>: the completion record</li><li style='list-style: initial'><b>completion_token</b>: the completion token</li></ul><p>Media files can be used with <code>{% url 'public_online_training_media' completion_token 'media_file_path' %}</code></p><p>Upon completion, call the JS function: <code>training_completed(dict_data)</code> to complete the training</p><p>Forms with ID <code>training-quiz-form</code> will automatically have the form data saved in the training attempt</p><p>To display user responses in the View Responses popup: Ensure that the keys in your <code>dataToSave</code> JSON object exactly match the id or name attributes of the input elements in your HTML</p>",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TrainingAttempt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("score_percentage", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(default=False)),
                (
                    "responses",
                    models.JSONField(blank=True, help_text="The exact payload submitted by the user.", null=True),
                ),
                (
                    "training_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="NEMO_online_training.trainingrecord",
                    ),
                ),
            ],
        ),
    ]
