# Generated by Django 5.2.17 on 2026-09-14 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def set_training_record_status(apps, schema_editor):
    TrainingRecord = apps.get_model("NEMO_online_training", "TrainingRecord")
    TrainingRecord.objects.filter(end__isnull=False).update(status="COMPLETED")


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_online_training", "0005_alter_traininguser_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="trigger_condition",
            field=models.CharField(
                choices=[("on_pass", "On Pass"), ("on_fail", "On Failure"), ("always", "Always")],
                default="on_pass",
                help_text="Select when this action should execute.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="answer_key",
            field=models.JSONField(
                blank=True,
                help_text="<p>JSON mapping of inputs to correct answers. Leave blank to only require completion.</p>",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="max_attempts",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Maximum allowed attempts. Set to 0 or leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="passing_score_percentage",
            field=models.IntegerField(
                blank=True,
                help_text="Required score to pass (e.g. 80). Leave blank if no quiz is required.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="retry_cooldown_minutes",
            field=models.IntegerField(
                blank=True, default=0, help_text="Wait time in minutes between failed attempts.", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="status",
            field=models.CharField(
                choices=[("COMPLETED", "Completed"), ("FAILED", "Failed"), ("IN_PROGRESS", "In Progress")],
                default="IN_PROGRESS",
                max_length=100,
            ),
        ),
        migrations.RunPython(set_training_record_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="training",
            name="html_content",
            field=models.TextField(
                blank=True,
                help_text="<p>The HTML content of the training. The following context variables are available:</p><ul style='padding-left: 35px;'><li style='list-style: initial'><b>training_user</b>: the user who is completing the training</li><li style='list-style: initial'><b>training</b>: the training being completed</li><li style='list-style: initial'><b>record</b>: the completion record</li><li style='list-style: initial'><b>completion_token</b>: the completion token</li></ul><p>Media files can be used with <code>{% url 'public_online_training_media' completion_token 'media_file_path' %}</code></p><p>Upon completion, call the JS function: <code>complete_training(button, dict_data|form)</code> to complete the training</p>",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TrainingAttempt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("score_percentage", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(default=False)),
                (
                    "responses",
                    models.JSONField(blank=True, help_text="The exact payload submitted by the user.", null=True),
                ),
                (
                    "training_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="NEMO_online_training.trainingrecord",
                    ),
                ),
            ],
        ),
    ]
