# Generated by Django 5.2.14 on 2026-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_online_training", "0006_training_answer_key_training_max_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="trigger_condition",
            field=models.CharField(
                choices=[("on_pass", "On Pass"), ("on_fail", "On Failure"), ("always", "Always")],
                default="on_pass",
                help_text="Select when this action should execute.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="html_content",
            field=models.TextField(
                blank=True,
                help_text="<p>The HTML content of the training. The following context variables are available:</p><ul style='padding-left: 35px;'><li style='list-style: initial'><b>training_user</b>: the user who is completing the training</li><li style='list-style: initial'><b>training</b>: the training being completed</li><li style='list-style: initial'><b>record</b>: the completion record</li><li style='list-style: initial'><b>completion_token</b>: the completion token</li></ul><p>Media files can be used with <code>{% url 'public_online_training_media' completion_token 'media_file_path' %}</code></p><p>Upon completion, call the JS function: <code>complete_training(button, data, event)</code> to complete the training</p><p>The legacy JS function will also still work: <code>training_completed(dict_data)</code></p><p>To display user responses in the View Responses popup: Ensure that the keys in your <code>dataToSave</code> JSON object exactly match the id or name attributes of the input elements in your HTML</p>",
                null=True,
            ),
        ),
    ]
